[package]
name = "rust-mongo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
async-trait = "0.1.63"
async_once = "0.2.6"
lazy_static = "1.4.0"
mongodb = { version = "2.3.1", features = ["bson-chrono-0_4"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
tokio = "1.24.2"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
